### ISSUE TITLE
Bot integration with Dynamics 365

### ISSUE THREAD

**Issue by Akash-Chatti** [ramarao9/CDSBot#7]
Can I know how the Bot is communicating with Dynamics 365 Omnichannel.
I see that the channel data in activity is being changed but how is the Omnichannel informed about this change

**Comment by ramarao9** [comment]
Hi @Akash-Chatti 

Communication between the Bot and Omnichannel is handled by the Omnichannel Middleware, that is provided using the Microsoft Nuget package Microsoft.Xrm.Omnichannel.BotSDK

https://docs.microsoft.com/en-us/dynamics365/customer-service/enable-bot-context

In this sample project, if you notice the below files, you will see how Omnichannel Middleware is setup and leveraged to communicate with the bot.

- Adding the Middlewares :  AdapterWithErrorHandler.cs
- Analyzing the messages on each turn: CustomMiddleware.cs
- Communicating with Omnichannel: OmniChannelBotClient.cs

Hope this answers your question.
